name = "Reason Interface"
code_fence_block_name = "reason"
grammar = "reason"
path_suffixes = ["rei"]
line_comments = ["//"]
block_comment = ["/* ", " */"]
autoclose_before = ";,=)}"
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true }
]
tab_size = 2
