name = "OCaml MLX"
grammar = "ocaml_mlx"
path_suffixes = ["mlx"]
block_comment = ["(* ", " *)"]
autoclose_before = ";,=)}]"
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "{|", end = "|", close = true, newline = true, not_in = ["string"] },
  { start = "[", end = "]", close = true, newline = true },
  { start = "[|", end = "|", close = true, newline = true, not_in = ["string"] },
  { start = "(", end = ")", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] }
]
tab_size = 2
