name = "Menhir"
grammar = "menhir"
path_suffixes = ["mly"]
block_comment = ["(* ", " *)"]
autoclose_before = ";,=)}]"
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "<", end = ">", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] }
]
tab_size = 2
